#!/bin/sh
# Git credential helper that returns username=git and password from $GITLAB_TOKEN
# Expects $GITLAB_TOKEN to be exported in the environment where git runs.
[ -z "$GITLAB_TOKEN" ] && exit 1
printf 'username=%s\npassword=%s\n' "git" "$GITLAB_TOKEN"
